### ISSUE TITLE
hddm-c is stricter that that in halld_recon

### ISSUE THREAD

**Issue by markito3** [rjones30/HDDM#2]
Trying to build the GlueX halld_recon package using this repository rather than the halld_recon-on-board versions of the hddm utilities. Getting the following error writing C code from an HDDM XML file:

`$ hddm-c -o .Linux_CentOS7-x86_64-gcc4.8.5-cntr/libraries/HDDM/hddm_mc_s libraries/HDDM/mc.xml`
`hddm-c: Template does not contain valid hddm header`

when using hddm-c built from this repository:

`$ which hddm-c`
`/data/scratch/hddm_standalone_build/gluex_top/hddm/hddm/bin/hddm-c`

The hddm-c from halld_recon seems fine with mc.xml as has been demonstrated by build after build, year after year.

**Comment by rjones30** [comment]
Lastest push to main branch fixes this problem. Please confirm. -Richard

**Comment by markito3** [comment]
Have confirmed that the problem has been fixed. Thanks @rjones30. Closing.
